services:
  backend-dev:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./.env:/app/.env
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package*.json
        - action: rebuild
          path: ./prisma
        - action: rebuild
          path: ./.env
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: db
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
